name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
          pwd
          ls
      - name: Checkout
        uses: actions/checkout@v2
      - name: Simple JS actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Abhijeet
      - name: Log  creating time
        run: echo "${{ steps.greet.outputs.time }}"
